"""
report_generator.py
-------------------
Generates a detailed text/CSV summary report and saves it to outputs/.
"""

import pandas as pd
import os
from src.analysis import (
    category_summary, monthly_trend, payment_method_analysis,
    budget_vs_actual, generate_insights, top_subcategories,
    quarterly_trend, weekend_vs_weekday
)


def generate_report(df: pd.DataFrame):
    os.makedirs("outputs", exist_ok=True)
    lines = []

    def h(text): lines.append(f"\n{'='*60}\n  {text}\n{'='*60}")
    def row(k, v): lines.append(f"  {k:<35} {v}")

    lines.append("=" * 60)
    lines.append("   EXPENSE TRACKER APP — ANNUAL REPORT 2024")
    lines.append("=" * 60)

    # ── Overview ──────────────────────────────────────────────────────────────
    h("📊 OVERVIEW")
    row("Total Records",       str(len(df)))
    row("Date Range",          f"{df['Date'].min().date()} → {df['Date'].max().date()}")
    row("Total Spend",         f"₹{df['Amount'].sum():,.2f}")
    row("Monthly Average",     f"₹{df['Amount'].sum()/12:,.2f}")
    row("Average Transaction", f"₹{df['Amount'].mean():,.2f}")
    row("Highest Transaction", f"₹{df['Amount'].max():,.2f}")
    row("Lowest Transaction",  f"₹{df['Amount'].min():,.2f}")

    # ── Category Summary ──────────────────────────────────────────────────────
    h("🏷️  CATEGORY-WISE SUMMARY")
    cat = category_summary(df)
    lines.append(cat.to_string(index=False))

    # ── Monthly Trend ─────────────────────────────────────────────────────────
    h("📅 MONTHLY TREND")
    lines.append(monthly_trend(df).to_string(index=False))

    # ── Quarterly ─────────────────────────────────────────────────────────────
    h("📆 QUARTERLY OVERVIEW")
    lines.append(quarterly_trend(df).to_string(index=False))

    # ── Payment Methods ───────────────────────────────────────────────────────
    h("💳 PAYMENT METHODS")
    lines.append(payment_method_analysis(df).to_string(index=False))

    # ── Weekend vs Weekday ────────────────────────────────────────────────────
    h("🗓️  WEEKEND vs WEEKDAY")
    lines.append(weekend_vs_weekday(df).to_string(index=False))

    # ── Budget Analysis ───────────────────────────────────────────────────────
    h("💰 BUDGET vs ACTUAL (Monthly Average)")
    lines.append(budget_vs_actual(df).to_string(index=False))

    # ── Top Subcategories ─────────────────────────────────────────────────────
    h("🔍 TOP 10 SUBCATEGORIES")
    lines.append(top_subcategories(df, 10).to_string(index=False))

    # ── Insights ──────────────────────────────────────────────────────────────
    h("💡 KEY INSIGHTS")
    for insight in generate_insights(df):
        lines.append(f"  {insight}")

    lines.append("\n" + "=" * 60)
    lines.append("  Report generated by Expense Tracker App")
    lines.append("=" * 60 + "\n")

    report_text = "\n".join(lines)

    # Save text report
    with open("outputs/expense_report.txt", "w", encoding="utf-8") as f:
        f.write(report_text)

    # Save category summary CSV
    cat.to_csv("outputs/category_summary.csv", index=False)

    # Save monthly summary CSV
    monthly_trend(df).to_csv("outputs/monthly_summary.csv", index=False)

    # Save budget analysis CSV
    budget_vs_actual(df).to_csv("outputs/budget_analysis.csv", index=False)

    print(report_text)
    print("\n✅  Reports saved:")
    print("    outputs/expense_report.txt")
    print("    outputs/category_summary.csv")
    print("    outputs/monthly_summary.csv")
    print("    outputs/budget_analysis.csv")


if __name__ == "__main__":
    df = pd.read_csv("data/expenses_clean.csv", parse_dates=["Date"])
    generate_report(df)
